import type { AbilityLevelDef, AnimalDef, SpeciesId } from "../domain/types";

const levelBonus = [0, 2, 4] as const;

function three(
  trigger: AbilityLevelDef["trigger"],
  amounts: readonly [number, number, number],
  make: (amount: number) => AbilityLevelDef["effects"],
  max?: readonly [number | undefined, number | undefined, number | undefined],
): readonly [AbilityLevelDef, AbilityLevelDef, AbilityLevelDef] {
  return [0, 1, 2].map((index) => ({
    trigger,
    effects: make(amounts[index]),
    maxTriggersPerBattle: max?.[index],
  })) as unknown as readonly [AbilityLevelDef, AbilityLevelDef, AbilityLevelDef];
}

export const ANIMALS: readonly AnimalDef[] = [
  {
    id: "hedgehog",
    nameZh: "刺猬",
    tier: 1,
    habitats: ["land"],
    baseAttack: 3,
    baseHealth: 5,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🦔", fallbackGlyph: "刺" },
    ability: {
      nameZh: "带刺反击",
      descriptionByLevel: ["受伤仍站立时反击 1 点。", "受伤仍站立时反击 2 点。", "受伤仍站立时反击 3 点，最多 3 次。"],
      levels: three("onHurt", [1, 2, 3], (amount) => [{ kind: "dealDamage", target: "attacker", amount }], [2, 2, 3]),
    },
  },
  {
    id: "frog",
    nameZh: "青蛙",
    tier: 1,
    habitats: ["water", "land"],
    baseAttack: 3,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐸", fallbackGlyph: "蛙" },
    ability: {
      nameZh: "后跃让位",
      descriptionByLevel: ["攻击后与最近后方同伴互换，补位同伴 +1 攻。", "攻击后与最近后方同伴互换，补位同伴 +2 攻。", "攻击后与最近后方同伴互换，补位同伴 +3 攻。"],
      levels: three("afterAttack", [1, 2, 3], (amount) => [{ kind: "swapSelfWithNearestAlly", direction: "behind", buffSwappedAllyAttack: amount }]),
    },
  },
  {
    id: "mussel",
    nameZh: "河蚌",
    tier: 1,
    habitats: ["water"],
    baseAttack: 2,
    baseHealth: 6,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🦪", fallbackGlyph: "蚌" },
    ability: {
      nameZh: "合拢贝壳",
      descriptionByLevel: ["首次受伤仍站立时获得 2 护盾。", "首次受伤仍站立时获得 3 护盾。", "首次受伤仍站立时获得 4 护盾。"],
      levels: three("onHurt", [2, 3, 4], (amount) => [{ kind: "gainShield", target: "self", amount }], [1, 1, 1]),
    },
  },
  {
    id: "swallow",
    nameZh: "燕子",
    tier: 1,
    habitats: ["air"],
    baseAttack: 2,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦", fallbackGlyph: "燕" },
    ability: {
      nameZh: "掠翼护前",
      descriptionByLevel: ["前排同伴获得 1 护盾。", "前排同伴获得 2 护盾。", "前排同伴获得 3 护盾。"],
      levels: three("battleStart", [1, 2, 3], (amount) => [{ kind: "gainShield", target: "allyFront", amount }]),
    },
  },
  {
    id: "otter",
    nameZh: "水獭",
    tier: 2,
    habitats: ["water", "land"],
    baseAttack: 4,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🦦", fallbackGlyph: "獭" },
    ability: {
      nameZh: "推波助阵",
      descriptionByLevel: ["前方同伴 +1 攻与 +1 体。", "前方同伴 +2 攻与 +2 体。", "前方同伴 +3 攻与 +3 体。"],
      levels: three("battleStart", [1, 2, 3], (amount) => [{ kind: "modifyAttack", target: "allyAheadSelf", amount }, { kind: "modifyHealth", target: "allyAheadSelf", amount }]),
    },
  },
  {
    id: "hare",
    nameZh: "野兔",
    tier: 2,
    habitats: ["land"],
    baseAttack: 3,
    baseHealth: 5,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐇", fallbackGlyph: "兔" },
    ability: {
      nameZh: "疾步蓄势",
      descriptionByLevel: ["攻击前自身 +1 攻，最多 2 次。", "攻击前自身 +2 攻，最多 2 次。", "攻击前自身 +3 攻，最多 2 次。"],
      levels: three("beforeAttack", [1, 2, 3], (amount) => [{ kind: "modifyAttack", target: "self", amount }], [2, 2, 2]),
    },
  },
  {
    id: "kingfisher",
    nameZh: "翠鸟",
    tier: 2,
    habitats: ["air", "water"],
    baseAttack: 4,
    baseHealth: 3,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦", fallbackGlyph: "翠" },
    ability: {
      nameZh: "俯冲点水",
      descriptionByLevel: ["对敌方后排造成 1 技能伤害。", "对敌方后排造成 2 技能伤害。", "对敌方后排造成 3 技能伤害。"],
      levels: three("battleStart", [1, 2, 3], (amount) => [{ kind: "dealDamage", target: "enemyBack", amount }]),
    },
  },
  {
    id: "carp",
    nameZh: "鲤鱼",
    tier: 2,
    habitats: ["water"],
    baseAttack: 2,
    baseHealth: 7,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐟", fallbackGlyph: "鲤" },
    ability: {
      nameZh: "余波护队",
      descriptionByLevel: ["退场后前排 +0 攻 +2 体。", "退场后前排 +1 攻 +3 体。", "退场后前排 +2 攻 +4 体。"],
      levels: [
        { trigger: "selfRetreat", effects: [{ kind: "modifyAttack", target: "allyFront", amount: 0 }, { kind: "modifyHealth", target: "allyFront", amount: 2 }] },
        { trigger: "selfRetreat", effects: [{ kind: "modifyAttack", target: "allyFront", amount: 1 }, { kind: "modifyHealth", target: "allyFront", amount: 3 }] },
        { trigger: "selfRetreat", effects: [{ kind: "modifyAttack", target: "allyFront", amount: 2 }, { kind: "modifyHealth", target: "allyFront", amount: 4 }] },
      ],
    },
  },
  {
    id: "crow",
    nameZh: "乌鸦",
    tier: 3,
    habitats: ["air", "land"],
    baseAttack: 4,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦‍⬛", fallbackGlyph: "乌" },
    ability: {
      nameZh: "拾势而起",
      descriptionByLevel: ["同伴退场后自身 +1 攻。", "同伴退场后自身 +2 攻。", "同伴退场后自身 +3 攻。"],
      levels: three("allyRetreat", [1, 2, 3], (amount) => [{ kind: "modifyAttack", target: "self", amount }]),
    },
  },
  {
    id: "pangolin",
    nameZh: "穿山甲",
    tier: 3,
    habitats: ["land"],
    baseAttack: 3,
    baseHealth: 8,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "", fallbackGlyph: "甲" },
    ability: {
      nameZh: "留甲护前",
      descriptionByLevel: ["退场后前排获得 2 护盾。", "退场后前排获得 3 护盾。", "退场后前排获得 4 护盾。"],
      levels: three("selfRetreat", [2, 3, 4], (amount) => [{ kind: "gainShield", target: "allyFront", amount }]),
    },
  },
  {
    id: "egret",
    nameZh: "白鹭",
    tier: 3,
    habitats: ["air", "water"],
    baseAttack: 5,
    baseHealth: 5,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦", fallbackGlyph: "鹭" },
    ability: {
      nameZh: "寻弱一击",
      descriptionByLevel: ["攻击前对最低体力敌人造成 2 技能伤害。", "攻击前造成 3 技能伤害。", "攻击前造成 4 技能伤害。"],
      levels: three("beforeAttack", [2, 3, 4], (amount) => [{ kind: "dealDamage", target: "enemyLowestHealth", amount }], [1, 1, 1]),
    },
  },
  {
    id: "weasel",
    nameZh: "小黄鼬",
    tier: 3,
    habitats: ["land"],
    baseAttack: 6,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "", fallbackGlyph: "鼬" },
    ability: {
      nameZh: "扰乱前排",
      descriptionByLevel: ["攻击后敌方前排 -1 攻。", "攻击后敌方前排 -2 攻。", "攻击后敌方前排 -3 攻。"],
      levels: three("afterAttack", [1, 2, 3], (amount) => [{ kind: "reduceAttack", target: "enemyFront", amount }], [2, 2, 2]),
    },
  },
  {
    id: "crucian_carp",
    nameZh: "鲫鱼",
    tier: 1,
    habitats: ["water"],
    baseAttack: 2,
    baseHealth: 6,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐟", fallbackGlyph: "鲫" },
    ability: {
      nameZh: "游影相随",
      descriptionByLevel: ["退场时在后方空位呼来 1/2 的燕影。", "退场时在后方空位呼来 1/3 的燕影。", "退场时在后方空位呼来 2/4 的燕影。"],
      levels: [
        { trigger: "selfRetreat", effects: [{ kind: "summonUnit", speciesId: "swallow", level: 1, attack: 1, health: 2, placement: "sourceThenBack" }] },
        { trigger: "selfRetreat", effects: [{ kind: "summonUnit", speciesId: "swallow", level: 1, attack: 1, health: 3, placement: "sourceThenBack" }] },
        { trigger: "selfRetreat", effects: [{ kind: "summonUnit", speciesId: "swallow", level: 1, attack: 2, health: 4, placement: "sourceThenBack" }] },
      ],
    },
  },
  {
    id: "red_bellied_squirrel",
    nameZh: "赤腹松鼠",
    tier: 2,
    habitats: ["land"],
    baseAttack: 3,
    baseHealth: 5,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐿️", fallbackGlyph: "松" },
    campModifiers: [{ kind: "modifyRefreshCost", amount: -1 }],
    ability: {
      nameZh: "藏果提醒",
      descriptionByLevel: ["战斗开始时随机同伴 +1 攻。", "战斗开始时随机同伴 +2 攻。", "战斗开始时随机同伴 +3 攻。"],
      levels: three("battleStart", [1, 2, 3], (amount) => [{ kind: "modifyAttack", target: "randomAlly", amount }]),
    },
  },
  {
    id: "yellow_weasel",
    nameZh: "黄鼬",
    tier: 2,
    habitats: ["land"],
    baseAttack: 4,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "", fallbackGlyph: "鼬" },
    ability: {
      nameZh: "扰阵推挤",
      descriptionByLevel: ["攻击后敌方前排 -1 攻并后退。", "攻击后敌方前排 -2 攻并后退。", "攻击后敌方前排 -3 攻并后退，最多 3 次。"],
      levels: three("afterAttack", [1, 2, 3], (amount) => [{ kind: "reduceAttack", target: "enemyFront", amount }, { kind: "pushTarget", target: "enemyFront", offset: 1 }], [2, 2, 3]),
    },
  },
  {
    id: "common_kingfisher",
    nameZh: "普通翠鸟",
    tier: 2,
    habitats: ["air", "water"],
    baseAttack: 4,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦", fallbackGlyph: "翠" },
    ability: {
      nameZh: "回身点水",
      descriptionByLevel: ["战斗开始对敌方后排造成 1 技能伤害。", "战斗开始对敌方后排造成 2 技能伤害。", "战斗开始对敌方后排造成 3 技能伤害。"],
      levels: three("battleStart", [1, 2, 3], (amount) => [{ kind: "dealDamage", target: "enemyBack", amount }]),
    },
  },
  {
    id: "spot_billed_duck",
    nameZh: "斑嘴鸭",
    tier: 2,
    habitats: ["water", "air"],
    baseAttack: 3,
    baseHealth: 6,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🦆", fallbackGlyph: "鸭" },
    ability: {
      nameZh: "并游护位",
      descriptionByLevel: ["战斗开始前排同伴获得 2 护盾。", "战斗开始前排同伴获得 3 护盾。", "战斗开始前排同伴获得 4 护盾。"],
      levels: three("battleStart", [2, 3, 4], (amount) => [{ kind: "gainShield", target: "allyFront", amount }]),
    },
  },
  {
    id: "mandarin_duck",
    nameZh: "鸳鸯",
    tier: 3,
    habitats: ["water", "air"],
    baseAttack: 4,
    baseHealth: 6,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🦆", fallbackGlyph: "鸳" },
    ability: {
      nameZh: "并影同行",
      descriptionByLevel: ["战斗开始同伴各获得 +1 攻。", "战斗开始同伴各获得 +2 攻。", "战斗开始同伴各获得 +3 攻。"],
      levels: three("battleStart", [1, 2, 3], (amount) => [{ kind: "modifyAttack", target: "allAllies", amount }]),
    },
  },
  {
    id: "night_heron",
    nameZh: "夜鹭",
    tier: 3,
    habitats: ["air", "water"],
    baseAttack: 5,
    baseHealth: 5,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦", fallbackGlyph: "夜" },
    ability: {
      nameZh: "夜色突袭",
      descriptionByLevel: ["攻击前对敌方后排造成 2 伤害，限 1 次。", "攻击前造成 3 伤害，限 1 次。", "攻击前造成 4 伤害，限 2 次。"],
      levels: three("beforeAttack", [2, 3, 4], (amount) => [{ kind: "dealDamage", target: "enemyBack", amount }], [1, 1, 2]),
    },
  },
  {
    id: "chinese_water_deer",
    nameZh: "河麂",
    tier: 3,
    habitats: ["land", "water"],
    baseAttack: 5,
    baseHealth: 7,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🦌", fallbackGlyph: "麂" },
    ability: {
      nameZh: "踏水冲阵",
      descriptionByLevel: ["攻击后将敌方前排后推并自身 +1 体。", "攻击后将敌方前排后推并自身 +2 体。", "攻击后将敌方前排后推并自身 +3 体。"],
      levels: three("afterAttack", [1, 2, 3], (amount) => [{ kind: "pushTarget", target: "enemyFront", offset: 1 }, { kind: "modifyHealth", target: "self", amount }], [2, 2, 3]),
    },
  },
  {
    id: "cabots_tragopan",
    nameZh: "黄腹角雉",
    tier: 4,
    habitats: ["land", "air"],
    baseAttack: 5,
    baseHealth: 8,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦", fallbackGlyph: "雉" },
    ability: {
      nameZh: "山雾合鸣",
      descriptionByLevel: ["战斗开始同伴各获得 +1 体。", "战斗开始同伴各获得 +2 体。", "战斗开始同伴各获得 +3 体。"],
      levels: three("battleStart", [1, 2, 3], (amount) => [{ kind: "modifyHealth", target: "allAllies", amount }]),
    },
  },
  {
    id: "chinese_alligator",
    nameZh: "扬子鳄",
    tier: 4,
    habitats: ["water", "land"],
    baseAttack: 6,
    baseHealth: 10,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐊", fallbackGlyph: "鳄" },
    ability: {
      nameZh: "伏水吞击",
      descriptionByLevel: ["受伤存活后咬击来源 2 伤害；若击倒则 +1 体。", "咬击 3 伤害；若击倒则 +2 体。", "咬击 4 伤害；若击倒则 +3 体，最多 2 次。"],
      levels: [
        { trigger: "onHurt", effects: [{ kind: "dealDamageAndGainOnRetreat", target: "attacker", damage: 2, healthGain: 1 }], maxTriggersPerBattle: 1 },
        { trigger: "onHurt", effects: [{ kind: "dealDamageAndGainOnRetreat", target: "attacker", damage: 3, healthGain: 2 }], maxTriggersPerBattle: 1 },
        { trigger: "onHurt", effects: [{ kind: "dealDamageAndGainOnRetreat", target: "attacker", damage: 4, healthGain: 3 }], maxTriggersPerBattle: 2 },
      ],
    },
  },
  {
    id: "sparrow",
    nameZh: "麻雀",
    tier: 1,
    habitats: ["air", "land"],
    baseAttack: 2,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦", fallbackGlyph: "雀" },
    ability: {
      nameZh: "惊飞警戒",
      descriptionByLevel: ["同伴退场后自身获得 1 护盾。", "同伴退场后自身获得 2 护盾。", "同伴退场后自身获得 3 护盾。"],
      levels: three("allyRetreat", [1, 2, 3], (amount) => [{ kind: "gainShield", target: "self", amount }], [3, 3, 3]),
    },
  },
  {
    id: "white_headed_bulbul",
    nameZh: "白头鹎",
    tier: 2,
    habitats: ["air", "land"],
    baseAttack: 3,
    baseHealth: 5,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦", fallbackGlyph: "鹎" },
    ability: {
      nameZh: "晨啼领队",
      descriptionByLevel: ["战斗开始后方同伴 +1 攻与 +1 体。", "战斗开始后方同伴 +2 攻与 +2 体。", "战斗开始后方同伴 +3 攻与 +3 体。"],
      levels: three("battleStart", [1, 2, 3], (amount) => [{ kind: "modifyAttack", target: "allyBack", amount }, { kind: "modifyHealth", target: "allyBack", amount }]),
    },
  },
  {
    id: "black_muntjac",
    nameZh: "黑麂",
    tier: 5,
    habitats: ["land"],
    baseAttack: 7,
    baseHealth: 9,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🦌", fallbackGlyph: "黑" },
    ability: {
      nameZh: "林影错步",
      descriptionByLevel: ["攻击前与最近后方同伴互换，补位同伴 +1 攻并获得 2 护盾。", "攻击前互换，补位同伴 +2 攻并获得 3 护盾。", "攻击前互换，补位同伴 +3 攻并获得 4 护盾。"],
      levels: [
        { trigger: "beforeAttack", effects: [{ kind: "swapSelfWithNearestAlly", direction: "behind", buffSwappedAllyAttack: 1 }, { kind: "gainShield", target: "allyAheadSelf", amount: 2 }], maxTriggersPerBattle: 1 },
        { trigger: "beforeAttack", effects: [{ kind: "swapSelfWithNearestAlly", direction: "behind", buffSwappedAllyAttack: 2 }, { kind: "gainShield", target: "allyAheadSelf", amount: 3 }], maxTriggersPerBattle: 1 },
        { trigger: "beforeAttack", effects: [{ kind: "swapSelfWithNearestAlly", direction: "behind", buffSwappedAllyAttack: 3 }, { kind: "gainShield", target: "allyAheadSelf", amount: 4 }], maxTriggersPerBattle: 2 },
      ],
    },
  },
] as const;

export const ANIMAL_BY_ID = Object.fromEntries(ANIMALS.map((animal) => [animal.id, animal])) as Record<SpeciesId, AnimalDef>;
