import type { AbilityLevelDef, AnimalDef, SpeciesId } from "../domain/types";

const levelBonus = [0, 2, 4] as const;

function three(
  trigger: AbilityLevelDef["trigger"],
  amounts: readonly [number, number, number],
  make: (amount: number) => AbilityLevelDef["effects"],
  max?: readonly [number | undefined, number | undefined, number | undefined],
): readonly [AbilityLevelDef, AbilityLevelDef, AbilityLevelDef] {
  return [0, 1, 2].map((index) => ({
    trigger,
    effects: make(amounts[index]),
    maxTriggersPerBattle: max?.[index],
  })) as unknown as readonly [AbilityLevelDef, AbilityLevelDef, AbilityLevelDef];
}

export const ANIMALS: readonly AnimalDef[] = [
  {
    id: "hedgehog",
    nameZh: "刺猬",
    tier: 1,
    habitats: ["land"],
    baseAttack: 3,
    baseHealth: 5,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🦔", fallbackGlyph: "刺" },
    ability: {
      nameZh: "带刺反击",
      descriptionByLevel: ["受伤仍站立时反击 1 点。", "受伤仍站立时反击 2 点。", "受伤仍站立时反击 3 点，最多 3 次。"],
      levels: three("onHurt", [1, 2, 3], (amount) => [{ kind: "dealDamage", target: "attacker", amount }], [2, 2, 3]),
    },
  },
  {
    id: "frog",
    nameZh: "青蛙",
    tier: 1,
    habitats: ["water", "land"],
    baseAttack: 3,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐸", fallbackGlyph: "蛙" },
    ability: {
      nameZh: "后跃让位",
      descriptionByLevel: ["攻击后后跃，补位同伴 +1 攻。", "攻击后后跃，补位同伴 +2 攻。", "攻击后后跃，补位同伴 +3 攻。"],
      levels: three("afterAttack", [1, 2, 3], (amount) => [{ kind: "moveSelf", offset: 1, buffPromotedAllyAttack: amount }]),
    },
  },
  {
    id: "mussel",
    nameZh: "河蚌",
    tier: 1,
    habitats: ["water"],
    baseAttack: 2,
    baseHealth: 6,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🦪", fallbackGlyph: "蚌" },
    ability: {
      nameZh: "合拢贝壳",
      descriptionByLevel: ["首次受伤仍站立时获得 2 护盾。", "首次受伤仍站立时获得 3 护盾。", "首次受伤仍站立时获得 4 护盾。"],
      levels: three("onHurt", [2, 3, 4], (amount) => [{ kind: "gainShield", target: "self", amount }], [1, 1, 1]),
    },
  },
  {
    id: "swallow",
    nameZh: "燕子",
    tier: 1,
    habitats: ["air"],
    baseAttack: 2,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦", fallbackGlyph: "燕" },
    ability: {
      nameZh: "掠翼护前",
      descriptionByLevel: ["前排同伴获得 1 护盾。", "前排同伴获得 2 护盾。", "前排同伴获得 3 护盾。"],
      levels: three("battleStart", [1, 2, 3], (amount) => [{ kind: "gainShield", target: "allyFront", amount }]),
    },
  },
  {
    id: "otter",
    nameZh: "水獭",
    tier: 2,
    habitats: ["water", "land"],
    baseAttack: 4,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🦦", fallbackGlyph: "獭" },
    ability: {
      nameZh: "推波助阵",
      descriptionByLevel: ["前方同伴 +1 攻与 +1 体。", "前方同伴 +2 攻与 +2 体。", "前方同伴 +3 攻与 +3 体。"],
      levels: three("battleStart", [1, 2, 3], (amount) => [{ kind: "modifyAttack", target: "allyAheadSelf", amount }, { kind: "modifyHealth", target: "allyAheadSelf", amount }]),
    },
  },
  {
    id: "hare",
    nameZh: "野兔",
    tier: 2,
    habitats: ["land"],
    baseAttack: 3,
    baseHealth: 5,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐇", fallbackGlyph: "兔" },
    ability: {
      nameZh: "疾步蓄势",
      descriptionByLevel: ["攻击前自身 +1 攻，最多 2 次。", "攻击前自身 +2 攻，最多 2 次。", "攻击前自身 +3 攻，最多 2 次。"],
      levels: three("beforeAttack", [1, 2, 3], (amount) => [{ kind: "modifyAttack", target: "self", amount }], [2, 2, 2]),
    },
  },
  {
    id: "kingfisher",
    nameZh: "翠鸟",
    tier: 2,
    habitats: ["air", "water"],
    baseAttack: 4,
    baseHealth: 3,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦", fallbackGlyph: "翠" },
    ability: {
      nameZh: "俯冲点水",
      descriptionByLevel: ["对敌方后排造成 1 技能伤害。", "对敌方后排造成 2 技能伤害。", "对敌方后排造成 3 技能伤害。"],
      levels: three("battleStart", [1, 2, 3], (amount) => [{ kind: "dealDamage", target: "enemyBack", amount }]),
    },
  },
  {
    id: "carp",
    nameZh: "鲫鱼",
    tier: 2,
    habitats: ["water"],
    baseAttack: 2,
    baseHealth: 7,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐟", fallbackGlyph: "鲫" },
    ability: {
      nameZh: "余波护队",
      descriptionByLevel: ["退场后前排 +0 攻 +2 体。", "退场后前排 +1 攻 +3 体。", "退场后前排 +2 攻 +4 体。"],
      levels: [
        { trigger: "selfRetreat", effects: [{ kind: "modifyAttack", target: "allyFront", amount: 0 }, { kind: "modifyHealth", target: "allyFront", amount: 2 }] },
        { trigger: "selfRetreat", effects: [{ kind: "modifyAttack", target: "allyFront", amount: 1 }, { kind: "modifyHealth", target: "allyFront", amount: 3 }] },
        { trigger: "selfRetreat", effects: [{ kind: "modifyAttack", target: "allyFront", amount: 2 }, { kind: "modifyHealth", target: "allyFront", amount: 4 }] },
      ],
    },
  },
  {
    id: "crow",
    nameZh: "乌鸦",
    tier: 3,
    habitats: ["air", "land"],
    baseAttack: 4,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦‍⬛", fallbackGlyph: "乌" },
    ability: {
      nameZh: "拾势而起",
      descriptionByLevel: ["同伴退场后自身 +1 攻。", "同伴退场后自身 +2 攻。", "同伴退场后自身 +3 攻。"],
      levels: three("allyRetreat", [1, 2, 3], (amount) => [{ kind: "modifyAttack", target: "self", amount }], [3, 3, 3]),
    },
  },
  {
    id: "pangolin",
    nameZh: "穿山甲",
    tier: 3,
    habitats: ["land"],
    baseAttack: 3,
    baseHealth: 8,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "", fallbackGlyph: "甲" },
    ability: {
      nameZh: "留甲护前",
      descriptionByLevel: ["退场后前排获得 2 护盾。", "退场后前排获得 3 护盾。", "退场后前排获得 4 护盾。"],
      levels: three("selfRetreat", [2, 3, 4], (amount) => [{ kind: "gainShield", target: "allyFront", amount }]),
    },
  },
  {
    id: "egret",
    nameZh: "白鹭",
    tier: 3,
    habitats: ["air", "water"],
    baseAttack: 5,
    baseHealth: 5,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "🐦", fallbackGlyph: "鹭" },
    ability: {
      nameZh: "寻弱一击",
      descriptionByLevel: ["攻击前对最低体力敌人造成 2 技能伤害。", "攻击前造成 3 技能伤害。", "攻击前造成 4 技能伤害。"],
      levels: three("beforeAttack", [2, 3, 4], (amount) => [{ kind: "dealDamage", target: "enemyLowestHealth", amount }], [1, 1, 1]),
    },
  },
  {
    id: "weasel",
    nameZh: "黄鼬",
    tier: 3,
    habitats: ["land"],
    baseAttack: 6,
    baseHealth: 4,
    levelAttackBonus: levelBonus,
    levelHealthBonus: levelBonus,
    visual: { emoji: "", fallbackGlyph: "鼬" },
    ability: {
      nameZh: "扰乱前排",
      descriptionByLevel: ["攻击后敌方前排 -1 攻。", "攻击后敌方前排 -2 攻。", "攻击后敌方前排 -3 攻。"],
      levels: three("afterAttack", [1, 2, 3], (amount) => [{ kind: "reduceAttack", target: "enemyFront", amount }], [2, 2, 2]),
    },
  },
] as const;

export const ANIMAL_BY_ID = Object.fromEntries(ANIMALS.map((animal) => [animal.id, animal])) as Record<SpeciesId, AnimalDef>;
